apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}-deployment
spec:
  selector:
    matchLabels:
      repo: bpcalc
  replicas: 1
  template:
    metadata:
      labels:
        repo: bpcalc
      annotations:
        vault.hashicorp.com/role: 'internal-app'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/agent-inject-secret-database-config.txt: 'internal/data/database/config'
    spec:
      serviceAccountName: internal-app
      containers:
      - name: {{ .Values.container.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: "PORT"
          value: "{{ .Values.container.port }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-app