replicaCount: 1

image:
  repository: gcr.io/tudublin/backend
  tag: v1.0.99-manual
  pullPolicy: Always

container:
  name: backend
  port: 9090

service:
  name: backend-service
  ingressName: be-ingress
  staticIP: backend-ip
  port: 80

deploy:
  name: backend-deployment
  label:
    dep: stable