name: Continuous Integration

on:
  push:
    branches: [ "feat/response" ]
  workflow_dispatch:

env:
  SONAR_ORG: hypheni
  SONAR_PROJ: go-bp-calc-k8s
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Git code checkout
        uses: actions/checkout@v3

      - name: Set up SonarCloud cache
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
        
      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=go-bp-calc-k8s
            -Dsonar.organization=hypheni
